/**
 * Invoice PDF Generator
 * Generates professional PDF invoices with configurable templates
 */

import { jsPDF } from 'jspdf';
import 'jspdf-autotable';

export interface InvoiceLineItem {
  id?: number;
  name: string;
  quantity: number;
  rate: number;
  total: number;
  project?: string;
  note?: string;
}

export interface InvoiceData {
  id: number;
  invoiceNumber: string;
  issuedOn: string;
  dueOn?: string;
  reference?: string;
  description?: string;
  amount: number;
  currency: string;
  customer?: {
    id: number;
    name: string;
    email?: string;
  };
  lineItems: InvoiceLineItem[];
}

export interface CompanyProfile {
  name: string;
  email?: string;
  phone?: string;
  address1?: string;
  address2?: string;
  currency?: string;
  logo?: string;
}

/**
 * Generate a professional PDF for invoices
 * @param invoices - Array of invoice data to include
 * @param company - Company profile information
 * @returns PDF content as Buffer
 */
export async function generateInvoicesPdf(
  invoices: InvoiceData[],
  company: CompanyProfile
): Promise<Buffer> {
  const pdf = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageHeight = pdf.internal.pageSize.getHeight();
  const pageWidth = pdf.internal.pageSize.getWidth();
  const margin = 20;
  let yPosition = margin;

  // Helper function to add a new page
  const addNewPage = () => {
    pdf.addPage();
    yPosition = margin;
  };

  // Header
  pdf.setFontSize(24);
  pdf.setFont(undefined, 'bold');
  pdf.text('INVOICE', margin, yPosition);
  yPosition += 15;

  // Company info
  pdf.setFontSize(11);
  pdf.setFont(undefined, 'normal');
  pdf.text(company.name || 'Company Name', margin, yPosition);
  yPosition += 6;
  if (company.email) {
    pdf.text(`Email: ${company.email}`, margin, yPosition);
    yPosition += 6;
  }
  if (company.phone) {
    pdf.text(`Phone: ${company.phone}`, margin, yPosition);
    yPosition += 6;
  }
  yPosition += 5;

  // Process each invoice
  for (let i = 0; i < invoices.length; i++) {
    const invoice = invoices[i];

    // Check if we need a new page
    if (yPosition > pageHeight - 60) {
      addNewPage();
    }

    // Invoice header
    pdf.setFontSize(12);
    pdf.setFont(undefined, 'bold');
    pdf.text(`Invoice #${invoice.invoiceNumber}`, margin, yPosition);
    yPosition += 8;

    // Invoice details
    pdf.setFontSize(10);
    pdf.setFont(undefined, 'normal');
    pdf.text(`Issued: ${invoice.issuedOn}`, margin, yPosition);
    yPosition += 5;
    if (invoice.dueOn) {
      pdf.text(`Due: ${invoice.dueOn}`, margin, yPosition);
      yPosition += 5;
    }
    if (invoice.reference) {
      pdf.text(`Reference: ${invoice.reference}`, margin, yPosition);
      yPosition += 5;
    }
    yPosition += 5;

    // Customer info
    if (invoice.customer) {
      pdf.setFont(undefined, 'bold');
      pdf.text('Bill To:', margin, yPosition);
      yPosition += 5;
      pdf.setFont(undefined, 'normal');
      pdf.text(invoice.customer.name, margin, yPosition);
      yPosition += 5;
      if (invoice.customer.email) {
        pdf.text(`Email: ${invoice.customer.email}`, margin, yPosition);
        yPosition += 5;
      }
      yPosition += 5;
    }

    // Line items table
    if (invoice.lineItems && invoice.lineItems.length > 0) {
      const tableData = invoice.lineItems.map((item) => [
        item.name,
        item.quantity.toString(),
        item.rate.toFixed(2),
        item.total.toFixed(2),
        item.project || '',
      ]);

      // Add total row
      tableData.push(['', '', '', invoice.amount.toFixed(2), '']);

      (pdf as any).autoTable({
        head: [['Description', 'Qty', 'Rate', 'Amount', 'Project']],
        body: tableData,
        startY: yPosition,
        margin: margin,
        headStyles: {
          fillColor: [30, 60, 120],
          textColor: [255, 255, 255],
          fontSize: 10,
          fontStyle: 'bold',
        },
        bodyStyles: {
          fontSize: 9,
        },
        footStyles: {
          fontStyle: 'bold',
          fontSize: 10,
        },
      });

      yPosition = (pdf as any).lastAutoTable.finalY + 10;
    }

    if (invoice.description) {
      pdf.setFontSize(10);
      pdf.setFont(undefined, 'normal');
      const descLines = pdf.splitTextToSize(
        `Notes: ${invoice.description}`,
        pageWidth - margin * 2
      );
      pdf.text(descLines, margin, yPosition);
      yPosition += descLines.length * 5 + 10;
    }

    yPosition += 10;
  }

  // Footer
  pdf.setFontSize(9);
  pdf.setTextColor(128, 128, 128);
  pdf.text(
    'Generated by FieldCost',
    pageWidth / 2,
    pageHeight - 10,
    { align: 'center' }
  );

  return Buffer.from(pdf.output('arraybuffer'));
}
